apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "appstudio.redhat.com/v1alpha1",
          "kind": "HASApplication",
          "metadata": {
            "name": "hasapplication-sample"
          },
          "spec": {
            "description": "application definition for petclinic-app",
            "displayName": "petclinic"
          }
        },
        {
          "apiVersion": "appstudio.redhat.com/v1alpha1",
          "kind": "HASComponent",
          "metadata": {
            "name": "hascomponent-sample-12345"
          },
          "spec": {
            "application": "hasapplication-sample-12345",
            "componentName": "backend",
            "env": [
              {
                "name": "FOO",
                "value": "foo1"
              },
              {
                "name": "BAR",
                "value": "bar1"
              }
            ],
            "replicas": 1,
            "resources": {
              "limits": {
                "cpu": "2",
                "ephemeral-storage": "500Mi",
                "memory": "500Mi",
                "storage": "400Mi"
              },
              "requests": {
                "cpu": "700m",
                "ephemeral-storage": "400Mi",
                "memory": "400Mi",
                "storage": "200Mi"
              }
            },
            "route": "route111",
            "source": {
              "git": {
                "url": "https://github.com/devfile-samples/devfile-sample-java-springboot-basic"
              }
            },
            "targetPort": 1111
          }
        },
        {
          "apiVersion": "appstudio.redhat.com/v1alpha1",
          "kind": "HASComponentDetectionQuery",
          "metadata": {
            "name": "hascomponentdetectionquery-sample"
          },
          "spec": {
            "foo": "bar"
          }
        },
        {
          "apiVersion": "appstudio.redhat.com/v1alpha1",
          "kind": "HASPush",
          "metadata": {
            "name": "haspush-sample"
          },
          "spec": {
            "foo": "bar"
          }
        }
      ]
    capabilities: Basic Install
    operators.operatorframework.io/builder: operator-sdk-v1.13.0+git
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v3
  name: application-service.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: HASApplication is the Schema for the hasapplications API
      displayName: HASApplication
      kind: HASApplication
      name: hasapplications.appstudio.redhat.com
      version: v1alpha1
    - description: HASComponentDetectionQuery is the Schema for the hascomponentdetectionqueries
        API
      displayName: HASComponent Detection Query
      kind: HASComponentDetectionQuery
      name: hascomponentdetectionqueries.appstudio.redhat.com
      version: v1alpha1
    - description: HASComponent is the Schema for the hascomponents API
      displayName: HASComponent
      kind: HASComponent
      name: hascomponents.appstudio.redhat.com
      version: v1alpha1
    - description: HASPush is the Schema for the haspushes API
      displayName: HASPush
      kind: HASPush
      name: haspushes.appstudio.redhat.com
      version: v1alpha1
  description: Hybrid Application Service operator
  displayName: Hybrid Application Service
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - appstudio.redhat.com
          resources:
          - hasapplications
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - appstudio.redhat.com
          resources:
          - hasapplications/finalizers
          verbs:
          - update
        - apiGroups:
          - appstudio.redhat.com
          resources:
          - hasapplications/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - appstudio.redhat.com
          resources:
          - hascomponentdetectionqueries
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - appstudio.redhat.com
          resources:
          - hascomponentdetectionqueries/finalizers
          verbs:
          - update
        - apiGroups:
          - appstudio.redhat.com
          resources:
          - hascomponentdetectionqueries/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - appstudio.redhat.com
          resources:
          - hascomponents
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - appstudio.redhat.com
          resources:
          - hascomponents/finalizers
          verbs:
          - update
        - apiGroups:
          - appstudio.redhat.com
          resources:
          - hascomponents/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - appstudio.redhat.com
          resources:
          - haspushes
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - appstudio.redhat.com
          resources:
          - haspushes/finalizers
          verbs:
          - update
        - apiGroups:
          - appstudio.redhat.com
          resources:
          - haspushes/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: application-service-controller-manager
      deployments:
      - name: application-service-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              labels:
                control-plane: controller-manager
            spec:
              containers:
              - args:
                - --secure-listen-address=0.0.0.0:8443
                - --upstream=http://127.0.0.1:8080/
                - --logtostderr=true
                - --v=10
                image: gcr.io/kubebuilder/kube-rbac-proxy:v0.8.0
                name: kube-rbac-proxy
                ports:
                - containerPort: 8443
                  name: https
                  protocol: TCP
                resources: {}
              - args:
                - --health-probe-bind-address=:8081
                - --metrics-bind-address=127.0.0.1:8080
                - --leader-elect
                command:
                - /manager
                image: maysunfaisal/hasoperator:latest
                imagePullPolicy: Always
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 8081
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  limits:
                    cpu: 200m
                    memory: 100Mi
                  requests:
                    cpu: 100m
                    memory: 20Mi
                securityContext:
                  allowPrivilegeEscalation: false
              securityContext:
                runAsNonRoot: true
              serviceAccountName: application-service-controller-manager
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: application-service-controller-manager
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - has
  - appstudio
  - redhat
  - kubernetes
  - application-service
  links:
  - name: Application Service
    url: https://application-service.domain
  maintainers:
  - email: jcollier@redhat.com
    name: John Collier
  - email: mfaisal@redhat.com
    name: Maysun Faisal
  - email: eyuen@redhat.com
    name: Elson Yuen
  maturity: alpha
  provider:
    name: Red Hat
  version: 0.0.1
