apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    rbac.authorization.k8s.io/aggregate-to-view: "true"
  name: application-service-push-viewer-role
rules:
- apiGroups:
  - appstudio.redhat.com
  resources:
  - pushes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - appstudio.redhat.com
  resources:
  - pushes/status
  verbs:
  - get
